workflows:
  react-native-android:
    name: React Native Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Unzip full project
        script: |
          unzip -o *.zip
          if [ -d "DalilakDawai" ]; then mv DalilakDawai/* . && mv DalilakDawai/.* . 2>/dev/null || true; Sub_Dir=$(find . -maxdepth 2 -name "android" -type d | head -n 1 | cut -d'/' -f2); if [ -n "$Sub_Dir" ] && [ "$Sub_Dir" != "android" ]; then mv "$Sub_Dir"/* . 2>/dev/null || true; fi; fi
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
